export enum ACCOUNT_STATUS {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    BLOCKED =  'BLOCKED',
    DELETED = 'DELETED'
}

export enum DEFAULT_USER_ROLES {
    SELLER = "SELLER",
    USER = "USER",
    MANAGER = "MANAGER",
    ADMIN = "ADMINISTRATOR"
}

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  AUDITOR = 'AUDITOR',
  REVIEWER = 'REVIEWER',
  VERIFIER = 'VERIFIER',
  CLIENT = 'CLIENT',
  CLIENT_ADMIN = 'CLIENT_ADMIN',
  CLIENT_ANALYST = 'CLIENT_ANALYST',
  CLIENT_AUDITOR = 'CLIENT_AUDITOR',
  CLIENT_REVIEWER = 'CLIENT_REVIEWER',
}

export enum ADMIN_ROLES {
    AUDITOR = "AUDITOR",
    REVIEWER = "REVIEWER",
    VERIFIER = "VERIFIER"
}

export enum CLIENT_ROLES {
    ADMIN = "ADMIN",
    ANALYST = "ANALYST",
    AUDITOR = "AUDITOR",
    REVIEWER = "REVIEWER"
}

export enum USER_TYPE {
    ADMIN = "SUPER_ADMIN",
    USER = "ADMIN",
    HOTEL = "CLIENT"
}

export enum SESSION_STATUS {
    LOGGED_IN = "LOGGED_IN",
    LOGGED_OUT = "LOGGED_OUT",
    BLOCKED = "BLOCKED"
}

export enum OTP_TYPE {
    REGISTER_OTP = "REGISTER_OTP",
    LOGIN_OTP = "LOGIN_OTP",
    FORGOT_PASSWORD_OTP = "FORGOT_PASSWORD_OTP",
    ADD_EMAIL = "ADD_EMAIL",
    ADD_PHONE_NO = "ADD_PHONE_NO",
    CUSTOM_LOGIN = "CUSTOM_LOGIN"
}

export enum OTP_SEND_ON {
    PHONE = "PHONE",
    EMAIL = "EMAIL",
}


export enum LOGIN_BY
{
    PHONE = "PHONE",
    EMAIL = "EMAIL",
}

export enum OTP_REQUEST_LIMITS {
    RESEND_OTP = 200 
}
